### ISSUE TITLE
In model_lstm.py line 188: error[i] = (x - x_p)/250*100  # (ms)

### ISSUE THREAD

**Issue by RayShark** [shipengai/ECG-Segment-LSTM#1]
Hi shipengai, I think it should be:
error[i] = (x - x_p)/250*1000  # (ms)
since 250Hz is the frequency of th signal, and (x - x_p)/250 refers to 1(s),
so if you want to transfer to (ms), maybe you should multiple 1000.

**Comment by shipengai** [comment]
Yes you are right。 Thanks
